We only need numpy for this tutorial.

In [292]:
import numpy as np

First, a motivating example for why we might want a NUMerical PYthon library.

In [293]:
import time
num_elements = 1000000
input_array = [i for i in range(num_elements)]

In [294]:
start_time = time.time()
return_array = [0 for i in range(len(input_array))]
for key, val in enumerate(input_array):
    return_array[key] = val * val
print(time.time() - start_time)

0.18476200103759766


In [295]:
start_time = time.time()
return_array_vectorized = np.power(input_array, 4)
print(time.time() - start_time)

0.06137800216674805


Array operations

Array construction

In [230]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [231]:
array_1 = np.array([[1,2],[3,4],[5,6]])
array_1

array([[1, 2],
       [3, 4],
       [5, 6]])

Array access

In [232]:
array_1[1,1]

4

In [233]:
array_1[1,:]

array([3, 4])

Array broadcasting of addition and scalar multiplication

In [234]:
array_2 = array_1 + 1
array_2

array([[2, 3],
       [4, 5],
       [6, 7]])

In [235]:
array_1 * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [236]:
array_1 / 2.0

array([[0.5, 1. ],
       [1.5, 2. ],
       [2.5, 3. ]])

Array elementwise addition

In [237]:
array_1 + array_2

array([[ 3,  5],
       [ 7,  9],
       [11, 13]])

Array elementwise multiplication

In [238]:
array_1 * array_1

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

Dot-product

In [239]:
array_3 = np.array([[1, 2]])
array_4 = np.array([[3], [4]])
np.dot(array_3, array_4)

array([[11]])

In [240]:
array_5 = np.dot(array_4, array_3)
array_5

array([[3, 6],
       [4, 8]])

Array info

In [241]:
array_5.sum(axis=0)

array([ 7, 14])

In [242]:
array_5.mean(axis=0)

array([3.5, 7. ])

In [243]:
array_5.std(axis=0)

array([0.5, 1. ])

In [244]:
array_5.max(axis=0)

array([4, 8])

In [245]:
array_5.shape

(2, 2)

Constructing matrices

In [176]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [43]:
M1 = np.matrix(array_1)
M1

matrix([[1, 2],
        [3, 4],
        [5, 6]])

Matrix operations.

Matrix transpose

In [186]:
M2 = np.matrix(array_2).T  # You cannot call transponse on an array!
# or np.matrix(array_2).transpose()
M2

matrix([[2, 4, 6],
        [3, 5, 7]])

Matrix elementwise multiplication

In [210]:
np.multiply(M2, M2)  # Note that * does not do elementwise multiplication for matrices, like it does for arrays!

matrix([[ 4, 16, 36],
        [ 9, 25, 49]])

Matrix elementwise exponentiation

In [217]:
np.power(M4, 2)

matrix([[  64,  196,  400],
        [ 324, 1024, 2116],
        [ 784, 2500, 5184]])

Matrix multiplication

In [211]:
M4 = np.matmul(M1, M2)  # np.matmul may be used for matrix multiplication instead of np.dot
# or np.dot(M1, M2), or M1 * M2
M4

matrix([[ 8, 14, 20],
        [18, 32, 46],
        [28, 50, 72]])

In [216]:
M4^2  # or np.matmul(M4, M4)

matrix([[  64,  196,  400],
        [ 324, 1024, 2116],
        [ 784, 2500, 5184]])

Matrix multiplication is not commutative

In [159]:
np.matmul(M1, M2).shape == np.matmul(M2, M1).shape

False

Matrix Inverse

In [160]:
M6 = np.matrix([[2, 0], [0, 2]])
np.linalg.inv(M6)

matrix([[0.5, 0. ],
        [0. , 0.5]])

Inverse fails if matrix is singular.

In [218]:
np.linalg.inv(M4)

LinAlgError: Singular matrix

Solving linear systems Ax = b for b

In [162]:
A1 = np.matrix([[1, 1], [0, 1]])  # 2x2
# Remember that a vector is a special case of a matrix.
x1 = np.matrix([[2], [2]])  # 2x1.  Note - np.matrix([[2, 2]]) is 1x2!
b1 = np.matmul(A1, x1)  # 2x1
b1

matrix([[4],
        [2]])

Solving linear systems Ax = b for x

In [163]:
x1_verify = np.linalg.solve(A1, b1)
all(x1 == x1_verify)

True

Another linear system that is overdetermined (no solution) when solving for x

In [164]:
A2 = np.matrix([[1, 1], [2, 2]])
x2 = np.matrix([[2], [3]])
b2 = np.matmul(A2, x2)
b2

matrix([[ 5],
        [10]])

In [165]:
x2_verify = np.linalg.solve(A2, b2)
x2_verify

LinAlgError: Singular matrix

Another linear system that is underdetermined (many solutions) when solving for x

In [166]:
A3 = np.matrix([[1, 0, 0], [0, 1, 1]])
x3 = np.matrix([[1], [1], [1]])
b3 = np.matmul(A3, x3)
b3

matrix([[1],
        [2]])

In [167]:
np.linalg.solve(A3, b3)

LinAlgError: Last 2 dimensions of the array must be square