In [94]:
import numpy as np
import time

First, a motivating example for why we might want a NUMerical PYthon (numpy) library.

In [95]:
num_elements = 1000000
input_array = np.arange(num_elements)

In [96]:
start_time = time.time()
return_array = [0] * len(input_array)
for key, val in enumerate(input_array):
    return_array[key] = val * val
print(time.time() - start_time)

0.22849106788635254


In [97]:
start_time = time.time()
return_array_vectorized = np.power(input_array, 2)
print(time.time() - start_time)

0.0030007362365722656


<b>Array operations</b>

Array construction

In [98]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [99]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [100]:
array_1 = np.array([[1,2],[3,4],[5,6]])  # An array with arbitrary elements.
array_1

array([[1, 2],
       [3, 4],
       [5, 6]])

Array access

In [102]:
array_1[1,1]  # Access an element

4

In [104]:
array_1[1,:]  # Access a row

array([3, 4])

Array broadcasting of addition and scalar multiplication

In [105]:
array_2 = array_1 + 1
array_2

array([[2, 3],
       [4, 5],
       [6, 7]])

In [107]:
array_1 * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [108]:
array_1 / 2.0

array([[0.5, 1. ],
       [1.5, 2. ],
       [2.5, 3. ]])

Array elementwise addition

In [109]:
array_1 + array_2

array([[ 3,  5],
       [ 7,  9],
       [11, 13]])

Array elementwise multiplication

In [112]:
np.multiply(array_1, array_1) #array_1 * array_1

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

Dot-product

In [114]:
array_3 = np.array([[1, 2]])
array_4 = np.array([[3], [4]])
np.dot(array_3, array_4)

array([[11]])

In [119]:
array_5 = np.dot(array_4, array_3)
array_5

array([[3, 6],
       [4, 8]])

Array info

In [120]:
array_5.sum(axis=1)

array([ 9, 12])

In [121]:
array_5.mean(axis=0)

array([3.5, 7. ])

In [122]:
array_5.std(axis=0)

array([0.5, 1. ])

In [123]:
array_5.max(axis=0)

array([4, 8])

In [125]:
array_5.shape

(2, 2)

Constructing matrices

In [126]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Transpose

In [128]:
M1 = array_1.T
M1

array([[1, 3, 5],
       [2, 4, 6]])

Matrix elementwise exponentiation

In [129]:
np.power(M1, 2)

array([[ 1,  9, 25],
       [ 4, 16, 36]])

Matrix multiplication

In [130]:
np.matmul(M1.T, M1)  # or np.dot(M1.T, M1)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

Matrix multiplication is not commutative

In [131]:
np.matmul(M1, M1.T).shape == np.matmul(M1.T, M1).shape

False

Matrix Inverse

In [132]:
np.linalg.inv(np.array([[2, 0], [0, 2]]))

array([[0.5, 0. ],
       [0. , 0.5]])

Inverse fails if matrix is singular.

In [134]:
np.linalg.inv(np.matmul(M1.T, M1))  # This should raise an exception.

LinAlgError: Singular matrix

Solving linear systems Ax = b for b

In [137]:
A1 = np.array([[1, 1], [0, 1]])
x1 = np.array([[2], [2]])
b1 = np.matmul(A1, x1)
b1

array([[4],
       [2]])

Solving linear systems Ax = b for x

In [138]:
x1_verify = np.linalg.solve(A1, b1)
all(x1 == x1_verify)

True

Another linear system that is overdetermined (no solution) when solving for x

In [139]:
A2 = np.array([[1, 1], [2, 2]])  # Note that the rank of this matrix is 1.
x2 = np.array([[2], [3]])
b2 = np.matmul(A2, x2)
b2

array([[ 5],
       [10]])

In [141]:
x2_verify = np.linalg.solve(A2, b2)  # This should raise an exception.

LinAlgError: Singular matrix

Another linear system that is underdetermined (many solutions) when solving for x

In [142]:
A3 = np.array([[1, 0, 0], [0, 1, 1]])
x3 = np.array([[1], [1], [1]])
b3 = np.matmul(A3, x3)
b3

array([[1],
       [2]])

In [143]:
np.linalg.solve(A3, b3)  # This should raise an exception.

LinAlgError: Last 2 dimensions of the array must be square