We only need numpy for this tutorial.

In [1]:
import numpy as np

First, a motivating example for why we might want a NUMerical PYthon library.

In [2]:
import time
num_elements = 1000000
input_array = [i for i in range(num_elements)]

In [3]:
start_time = time.time()
return_array = [0 for i in range(len(input_array))]
for key, val in enumerate(input_array):
    return_array[key] = val * val
print(time.time() - start_time)

0.17403483390808105


In [4]:
start_time = time.time()
return_array_vectorized = np.power(input_array, 4)
print(time.time() - start_time)

0.058896780014038086


Array operations

Array construction

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
array_1 = np.array([[1,2],[3,4],[5,6]])
array_1

array([[1, 2],
       [3, 4],
       [5, 6]])

Array access

In [7]:
array_1[1,1]

4

In [8]:
array_1[1,:]

array([3, 4])

Array broadcasting of addition and scalar multiplication

In [9]:
array_2 = array_1 + 1
array_2

array([[2, 3],
       [4, 5],
       [6, 7]])

In [10]:
array_1 * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [11]:
array_1 / 2.0

array([[0.5, 1. ],
       [1.5, 2. ],
       [2.5, 3. ]])

Array elementwise addition

In [237]:
array_1 + array_2

array([[ 3,  5],
       [ 7,  9],
       [11, 13]])

Array elementwise multiplication

In [238]:
array_1 * array_1

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

Dot-product

In [239]:
array_3 = np.array([[1, 2]])
array_4 = np.array([[3], [4]])
np.dot(array_3, array_4)

array([[11]])

In [240]:
array_5 = np.dot(array_4, array_3)
array_5

array([[3, 6],
       [4, 8]])

Array info

In [241]:
array_5.sum(axis=0)

array([ 7, 14])

In [242]:
array_5.mean(axis=0)

array([3.5, 7. ])

In [243]:
array_5.std(axis=0)

array([0.5, 1. ])

In [244]:
array_5.max(axis=0)

array([4, 8])

In [245]:
array_5.shape

(2, 2)

Constructing matrices

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Matrix operations.

Matrix transpose

In [26]:
M1 = array_2.T  # You cannot call transponse on an array!
# or np.matrix(array_2).transpose()
M1

array([[2, 4, 6],
       [3, 5, 7]])

Matrix elementwise multiplication

In [27]:
M2 = np.dot(array_2, M1)  # Note that * does not do elementwise multiplication for matrices, like it does for arrays!
M2

array([[13, 23, 33],
       [23, 41, 59],
       [33, 59, 85]])

Matrix elementwise exponentiation

In [28]:
np.power(M2, 2)

array([[ 169,  529, 1089],
       [ 529, 1681, 3481],
       [1089, 3481, 7225]])

Matrix multiplication

In [44]:
M3 = np.matmul(M1.T, M1)  # np.matmul may be used for matrix multiplication instead of np.dot
# or np.dot(M1, M2)
M3

array([[13, 23, 33],
       [23, 41, 59],
       [33, 59, 85]])

Matrix multiplication is not commutative

In [45]:
np.matmul(M1, M1.T).shape == np.matmul(M1.T, M1).shape

False

Matrix Inverse

In [46]:
np.linalg.inv(np.array([[2, 0], [0, 2]]))

array([[0.5, 0. ],
       [0. , 0.5]])

Inverse fails if matrix is singular.

In [47]:
np.linalg.inv(M3)

LinAlgError: Singular matrix

Solving linear systems Ax = b for b

In [48]:
A1 = np.array([[1, 1], [0, 1]])  # 2x2
# Remember that a vector is a special case of a matrix.
x1 = np.array([[2], [2]])  # 2x1.  Note - np.matrix([[2, 2]]) is 1x2!
b1 = np.matmul(A1, x1)  # 2x1
b1

array([[4],
       [2]])

Solving linear systems Ax = b for x

In [49]:
x1_verify = np.linalg.solve(A1, b1)
all(x1 == x1_verify)

True

Another linear system that is overdetermined (no solution) when solving for x

In [50]:
A2 = np.array([[1, 1], [2, 2]])
x2 = np.array([[2], [3]])
b2 = np.matmul(A2, x2)
b2

array([[ 5],
       [10]])

In [51]:
x2_verify = np.linalg.solve(A2, b2)
x2_verify

LinAlgError: Singular matrix

Another linear system that is underdetermined (many solutions) when solving for x

In [52]:
A3 = np.array([[1, 0, 0], [0, 1, 1]])
x3 = np.array([[1], [1], [1]])
b3 = np.matmul(A3, x3)
b3

array([[1],
       [2]])

In [53]:
np.linalg.solve(A3, b3)

LinAlgError: Last 2 dimensions of the array must be square