In [13]:
import numpy as np
import time

For this exercise you will be provided with a problem and and asked to construct two solutions.  The first solution should be without numpy and the second with numpy.  The vectorized forms with numpy should perform magnitudes more quickly.

In [14]:
arg_length = 1000000
arg_vector = np.arange(arg_length)  # An example vector argument.
print(f"Vector argument: {arg}")

num_rows, num_cols = 1000, 100
arg_matrix = np.array([[i + j for j in range(num_cols)] for i in range(num_rows)])  # An example matrix argument.
print(f"Matrix argument: {arg_2}")

Vector argument: [     0      1      2 ... 999997 999998 999999]
Matrix argument: [[   0    1    2 ...   97   98   99]
 [   1    2    3 ...   98   99  100]
 [   2    3    4 ...   99  100  101]
 ...
 [ 997  998  999 ... 1094 1095 1096]
 [ 998  999 1000 ... 1095 1096 1097]
 [ 999 1000 1001 ... 1096 1097 1098]]


<b>Problem 1</b>:  Construct a function which takes a vector, and returns an vector with each element doubled.

In [25]:
def doubler(x):
    """Take an array and return an array with each element doubled.  This version does not use numpy.
    
    :param x: An array of numbers.
    :return: An array of doubled numbers.
    """  
    new_x = [None] * len(x)
    for i in range(len(x)):
        new_x[i] = x[i] * 2
    return new_x

start_time = time.time()
print(doubler(arg_vector)[:5])
print(f"Runtime: {time.time() - start_time}")

[0, 2, 4, 6, 8]
Runtime: 0.2414090633392334


In [26]:
def doubler_vectorized(x):
    """Take an array and return an array with each element doubled.  This version uses numpy.
    
    :param x: An array of numbers.
    :return: An array of doubled numbers.
    """ 
    return x * 2

start_time = time.time()
print(doubler_vectorized(arg_vector)[:5])
print(f"Runtime: {time.time() - start_time}")

[0 2 4 6 8]
Runtime: 0.0014040470123291016


<b>Problem 2</b>: Construct a function which takes two vectors and returns the elementwise summation.

In [28]:
def adder(a, b):
    """Take two arrays and return an array with their elementwise addition.  This version does not use numpy.
    
    :param a: An array of numbers.
    :param b: An array of numbers.
    :return: An array of the elementwise addition of a and b.
    """ 
    c = [None] * len(a)
    for i in range(len(a)):
        c[i] = a[i] + b[i]
    return c
            
start_time = time.time()
print(adder(arg_vector, arg_vector)[:5])
print(f"Runtime: {time.time() - start_time}")

[0, 2, 4, 6, 8]
Runtime: 0.23424196243286133


In [30]:
def adder_vectorized(a, b):
    """Take two arrays and return an array with their elementwise addition.  This version uses numpy.
    
    :param a: An array of numbers.
    :param b: An array of numbers.
    :return: An array of the elementwise addition of a and b.
    """
    return a + b

start_time = time.time()
print(adder_vectorized(arg, arg)[:5])
print(f"Runtime: {time.time() - start_time}")

[0 2 4 6 8]
Runtime: 0.0013267993927001953


<b>Problem 3</b>: Construct a function which takes a matrix and returns the tranpose.

In [40]:
def transposer(A):
    """Take an mxn matrix (with m,n > 0) and return a nxm matrix with the transpose.
    
    :param A: A mxn matrix.
    :return: A nxm matrix.
    """  
    num_rows_input, num_cols_input = A.shape
    A_transpose = [[None] * num_rows_input] * num_cols_input
    for i in range(num_rows_input):
        for j in range(num_cols_input):
            A_transpose[j][i] = A[i, j]
    return A_transpose

start_time = time.time()
print(transposer(arg_2)[0][:5])
print(f"Runtime: {time.time() - start_time}")

[99, 100, 101, 102, 103]
Runtime: 0.02034592628479004


In [41]:
def transposer_numpy(A):
    """Take an mxn matrix (with m,n > 0) and return a nxm matrix with the transpose.
    
    :param A: A mxn matrix.
    :return: A nxm matrix.
    """  
    return A.T

start_time = time.time()
print(transposer(arg_2)[0][:5])
print(f"Runtime: {time.time() - start_time}")

[99, 100, 101, 102, 103]
Runtime: 0.020301103591918945
